version: '3.8'
services:
  dev-db:
    image: postgres:12.2
    container_name: dev-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - .local/data:/var/lib/postgresql/data
